#!/bin/sh /etc/rc.common

START=99
STOP=10

USE_PROCD=1
PROG=/usr/bin/beszel-agent

start_service() {
	local enabled port key
	
	config_load 'beszel-agent'
	config_get_bool enabled 'agent' 'enabled' '0'
	config_get port 'agent' 'port' '45876'
	config_get key 'agent' 'public_key' ''
	
	[ "$enabled" -eq 0 ] && return 0

	[ -z "$key" ] && {
		logger -t beszel-agent "Public key not set!"
		return 1
	}
	
	procd_open_instance beszel-agent
	procd_set_param command "$PROG" -listen "$port" -key "$key"
	procd_set_param respawn 3600 5 5
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param user root
	procd_close_instance
}

stop_service() {
	service_stop "$PROG"
}
